"""add_producto_nombre_to_order_item

Revision ID: e4e858e5f6cf
Revises: 
Create Date: 2026-05-20 14:04:59.792970
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e4e858e5f6cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('producto_nombre', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'producto_nombre')
    # ### end Alembic commands ###
